import { useEffect, useRef } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import type { Shipment } from "./App";

const makeMaterial=(color:number,metalness=.25)=>new THREE.MeshStandardMaterial({color,roughness:.68,metalness});
function box(w:number,h:number,d:number,material:THREE.Material,x=0,y=0,z=0){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;return mesh}
function addFactory(scene:THREE.Scene,x:number,z:number,scale=1){const steel=makeMaterial(0x39434a,.4),dark=makeMaterial(0x171c20),orange=makeMaterial(0xe87920,.35),glass=new THREE.MeshStandardMaterial({color:0x75aebf,emissive:0x16333c,emissiveIntensity:1.4});const g=new THREE.Group();g.position.set(x,0,z);g.scale.setScalar(scale);g.add(box(22,.25,17,makeMaterial(0x252b30),0,.12,0),box(18,4,11,steel,0,2,0),box(6,6,11,dark,-5,5,0));for(let i=-7;i<=7;i+=3.5)g.add(box(2.2,1.2,.12,glass,i,2.1,-5.56));for(let i=-6;i<=6;i+=4){const pipe=new THREE.Mesh(new THREE.CylinderGeometry(.65,.9,9,12),dark);pipe.position.set(i,8,2);pipe.castShadow=true;g.add(pipe);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.8,.8,.4,12),orange);cap.position.set(i,12.5,2);g.add(cap)}scene.add(g)}
function addWarehouse(scene:THREE.Scene,x:number,z:number,rotation=0){const g=new THREE.Group();g.position.set(x,0,z);g.rotation.y=rotation;g.add(box(15,3.5,8,makeMaterial(0x465158,.35),0,1.8,0));for(let i=-5;i<=5;i+=5)g.add(box(3,2.2,.15,makeMaterial(0x171c20),i,1.2,-4.08));g.add(box(15.5,.35,8.5,makeMaterial(0xd77322),0,3.65,0));scene.add(g)}
function addRoad(scene:THREE.Scene,a:THREE.Vector3,b:THREE.Vector3){const length=a.distanceTo(b),road=box(2.5,.12,length,makeMaterial(0x202428),0,.08,0);road.position.copy(a).lerp(b,.5);road.lookAt(b);scene.add(road);const line=box(.1,.14,length,new THREE.MeshBasicMaterial({color:0xd59a42}),0,.14,0);line.position.copy(road.position);line.rotation.copy(road.rotation);scene.add(line)}
function addTruck(scene:THREE.Scene,index:number){const g=new THREE.Group();g.add(box(1.4,1.1,2.2,makeMaterial(index%2?0x53616a:0xd46f1e,.45),0,1,0),box(1.45,1.5,1.3,makeMaterial(0xe87920,.4),0,1.15,-1.75));for(const z of [-2,-.6,1])for(const x of [-.78,.78]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.33,.33,.24,12),makeMaterial(0x101316));wheel.rotation.z=Math.PI/2;wheel.position.set(x,.43,z);g.add(wheel)}g.scale.setScalar(.75);scene.add(g);return g}

export default function IndustrialMap3D({shipments}:{shipments:Shipment[]}){
  const mount=useRef<HTMLDivElement>(null);const active=shipments.filter(s=>s.status==="ASSIGNED"||s.status==="IN_TRANSIT");const activeKey=active.map(s=>`${s.id}:${s.progressPercent}`).join("|");
  useEffect(()=>{const host=mount.current;if(!host)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x10171c);scene.fog=new THREE.FogExp2(0x10171c,.012);const camera=new THREE.PerspectiveCamera(48,host.clientWidth/host.clientHeight,.1,500);camera.position.set(48,42,58);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.appendChild(renderer.domElement);
    scene.add(new THREE.HemisphereLight(0x91b4ca,0x17130e,1.6));const sun=new THREE.DirectionalLight(0xffd0a0,3.2);sun.position.set(-25,45,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-60;sun.shadow.camera.right=60;sun.shadow.camera.top=60;sun.shadow.camera.bottom=-60;scene.add(sun);const ground=new THREE.Mesh(new THREE.PlaneGeometry(130,100),makeMaterial(0x263229));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);const grid=new THREE.GridHelper(130,65,0x46515a,0x303b42);grid.position.y=.03;scene.add(grid);
    addFactory(scene,-17,-8,1.15);addFactory(scene,24,-20,.75);addWarehouse(scene,14,17,.25);addWarehouse(scene,-27,24,-.2);const hubs=[new THREE.Vector3(-30,.15,30),new THREE.Vector3(-18,.15,-8),new THREE.Vector3(14,.15,17),new THREE.Vector3(28,.15,-22)];addRoad(scene,hubs[0],hubs[1]);addRoad(scene,hubs[1],hubs[2]);addRoad(scene,hubs[2],hubs[3]);addRoad(scene,hubs[1],hubs[3]);for(let i=0;i<24;i++)scene.add(box(3,.9,1.2,makeMaterial([0x9b4b2c,0x3b6573,0x696d43][i%3]),15+(i%6)*3.2,.55+Math.floor(i/12),24+Math.floor(i/6)*1.4));const trucks=active.map((_,i)=>addTruck(scene,i));
    const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=22;controls.maxDistance=115;controls.maxPolarAngle=Math.PI*.47;const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};window.addEventListener("resize",resize);let frame=0;const clock=new THREE.Clock();const animate=()=>{frame=requestAnimationFrame(animate);const t=clock.getElapsedTime();trucks.forEach((g,i)=>{const p=((active[i].progressPercent/100)+t*.015+i*.17)%1,segment=Math.min(2,Math.floor(p*3)),local=p*3-segment;g.position.copy(hubs[segment]).lerp(hubs[segment+1],local);g.position.y=.18;g.lookAt(hubs[segment+1])});controls.update();renderer.render(scene,camera)};animate();return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",resize);controls.dispose();renderer.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});if(renderer.domElement.parentNode===host)host.removeChild(renderer.domElement)}} , [activeKey]);
  return <section><div className="mapToolbar"><div><small>JUMEAU NUMÉRIQUE · TEMPS RÉEL</small><h2>Monde industriel 3D</h2></div><div><span className="legend orange"></span> Convoi actif <span className="legend white"></span> Site industriel</div></div><div className="map3d" ref={mount}><div className="map3dHelp">SOURIS · ROTATION &nbsp; MOLETTE · ZOOM &nbsp; CLIC DROIT · DÉPLACEMENT</div><div className="mapPanel"><small>RÉSEAU LOGISTIQUE</small><strong>{active.length} convois actifs</strong><span>2 usines · 2 entrepôts</span><span>{shipments.filter(s=>s.status==="OPEN").length} contrats disponibles</span></div></div></section>
}
